/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Student;
import model.StudentDao;



/**
 *
 * @author This PC
 */
public class StudentDialog extends javax.swing.JDialog {

    SimpleDateFormat date_Format = new SimpleDateFormat ("dd/MM/yyyy");
    StudentDao dao = new StudentDao();
    String strImage = null;
    /**
     * Creates new form StudentDialog
     */
    public StudentDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public void fillDataTable(){
        DefaultTableModel model= (DefaultTableModel)tbStudent.getModel();
        model.setRowCount(0);
        for (Student s : dao.getAllStudents()){
            Object rowData[]=new Object[6];
            
            rowData[0]= s.getID();
            rowData[1]= s.getName();
            rowData[2]= s.isSex()?"Male":"Female";
            rowData[3]= s.getBrithDate();
            rowData[4]= s.getAddress();
            rowData[5]= s.getImage();
            model.addRow(rowData);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        TxtIDStudent = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TxtNameStudent = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        rdMale = new javax.swing.JCheckBox();
        rdFemale = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TxtBrithday = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lblImage = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        BtnCreate = new javax.swing.JButton();
        BtnSave = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbStudent = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Manegement Student");

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));
        jPanel1.setForeground(new java.awt.Color(102, 255, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(450, 110));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 150));

        jPanel5.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel5.setLayout(new java.awt.BorderLayout(0, 4));

        TxtIDStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIDStudentActionPerformed(evt);
            }
        });
        jPanel5.add(TxtIDStudent, java.awt.BorderLayout.CENTER);

        jLabel2.setBackground(new java.awt.Color(51, 255, 204));
        jLabel2.setForeground(new java.awt.Color(51, 255, 204));
        jLabel2.setText("ID");
        jPanel5.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel5);

        jPanel6.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel6.setLayout(new java.awt.BorderLayout(0, 4));

        jLabel3.setText("Name");
        jPanel6.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        TxtNameStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNameStudentActionPerformed(evt);
            }
        });
        jPanel6.add(TxtNameStudent, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        jPanel7.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel7.setRequestFocusEnabled(false);
        jPanel7.setLayout(new java.awt.BorderLayout(0, 10));

        buttonGroup1.add(rdMale);
        rdMale.setSelected(true);
        rdMale.setText("Male");
        jPanel7.add(rdMale, java.awt.BorderLayout.WEST);

        buttonGroup1.add(rdFemale);
        rdFemale.setText("Female");
        jPanel7.add(rdFemale, java.awt.BorderLayout.CENTER);

        jLabel5.setText("Sex");
        jPanel7.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel7);

        jPanel9.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel9.setLayout(new java.awt.BorderLayout(0, 4));

        jLabel6.setText("BrithDay");
        jPanel9.add(jLabel6, java.awt.BorderLayout.PAGE_START);
        jPanel9.add(TxtBrithday, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel9);

        jPanel10.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel10.setLayout(new java.awt.BorderLayout(0, 4));

        jLabel7.setText("Address");
        jPanel10.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        txtAddress.setPreferredSize(new java.awt.Dimension(100, 120));
        jScrollPane1.setViewportView(txtAddress);

        jPanel10.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel10);

        lblImage.setText("Image Student");
        lblImage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImageMouseClicked(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(102, 255, 204));

        BtnCreate.setBackground(new java.awt.Color(51, 255, 51));
        BtnCreate.setText("Create");
        BtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateActionPerformed(evt);
            }
        });

        BtnSave.setBackground(new java.awt.Color(255, 255, 51));
        BtnSave.setText("Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        BtnUpdate.setBackground(new java.awt.Color(51, 255, 204));
        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnDelete.setBackground(new java.awt.Color(255, 51, 51));
        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCreate)
                    .addComponent(BtnUpdate))
                .addGap(55, 55, 55)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnDelete)
                    .addComponent(BtnSave))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCreate)
                    .addComponent(BtnSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnUpdate)
                    .addComponent(BtnDelete))
                .addGap(17, 17, 17))
        );

        tbStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Date", "Sex", "Address", "Image"
            }
        ));
        tbStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbStudentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbStudent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 341, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtIDStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDStudentActionPerformed

    public void reset(){
        txtAddress.setText("");
        TxtIDStudent.setText("");
        TxtBrithday.setText("");
        TxtNameStudent.setText("");
        rdMale.isSelected();
        lblImage.setText("Image");
        lblImage.setIcon(null);
        strImage = null;
    }
    private void BtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateActionPerformed
        // TODO add your handling code here:
       reset();
      
    }//GEN-LAST:event_BtnCreateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        if(TxtIDStudent.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "You have not entered the student code to delete");
        
        }
        else{
            if (dao.delStudentByID(TxtIDStudent.getText())>0){
                JOptionPane.showMessageDialog(this, "Delet Succesfull");
                fillDataTable();
            }
            else{
                JOptionPane.showMessageDialog(this, "Don't find the student to delete");
            }
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseClicked
        // TODO add your handling code here:
       try{ 
        JFileChooser jfc =new JFileChooser();
        jfc.showOpenDialog(null);
        File file = jfc.getSelectedFile();
        Image img = ImageIO.read(file);
        strImage=file.getName();
        lblImage.setText("");
        int width= lblImage.getWidth();
        int height= lblImage.getHeight();
        lblImage.setIcon(new ImageIcon(img.getScaledInstance(width,height,0)));
        
           }catch(IOException ex){
               System.out.println("Error:"+ex.toString());
           }
        
    }//GEN-LAST:event_lblImageMouseClicked
    public boolean validateForm(){
        if(TxtIDStudent.getText().isEmpty()|| TxtNameStudent.getText().isEmpty()){
            return false;
        }
        if ( TxtBrithday.getText().isEmpty() || txtAddress.getText().isEmpty()) {
            return false;
        }      
return true;
    }
    public Student getModel()throws ParseException{
        Student s = new Student();
        s.setID(TxtIDStudent.getText());
        s.setName(TxtNameStudent.getText());
        boolean gt =false;
        if (rdMale.isSelected()) {
            gt = true;
        }
        s.setSex(gt);
        s.setAddress(txtAddress.getText());
        s.setBrithDate(TxtBrithday.getText());
        
        if(strImage == null){
            s.setImage("No Avatar");
        }
        else{
            s.setImage(strImage);
        }
        return s;
        
    }
    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:
        if(validateForm()){
            try {
                Student s= getModel();
                if(dao.add(s)>0){
                    JOptionPane.showMessageDialog(this, "Save successfull");
                    fillDataTable();
                }
               } catch (ParseException ex) {
                Logger.getLogger(StudentDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "You have not entered complete information");
        }
    }//GEN-LAST:event_BtnSaveActionPerformed

    public void setModel (Student s){
        TxtIDStudent.setText(s.getID());
        TxtNameStudent.setText(s.getName());
//        TxtBrithday.setText(date_Format.format(s.getBrithDate()));
        TxtBrithday.setText(s.getBrithDate());
        txtAddress.setText(s.getAddress());
        boolean gt =s.isSex();
        if(s.isSex()){
            rdMale.isSelected();
        }else{
            rdFemale.isSelected();
        }
        if(s.getImage().equalsIgnoreCase("no avata")){
            lblImage.setText("NO AVATAR");
            lblImage.setIcon(null);
        }
        else{
        lblImage.setText("");
        ImageIcon imgIcon= new ImageIcon(getClass().getResource("/images/"+s.getImage()));
        Image img= imgIcon.getImage();
        img.getScaledInstance(lblImage.getWidth(),lblImage.getY(),0);
        }
        
    }
    
    private void tbStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbStudentMouseClicked
        // TODO add your handling code here:
        int id =tbStudent.rowAtPoint(evt.getPoint());
        String ID= tbStudent.getValueAt(id, 0).toString();
        Student s = dao.getStudentByID(ID);
        setModel(s);
    }//GEN-LAST:event_tbStudentMouseClicked

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        // TODO add your handling code here:
       
       
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void TxtNameStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNameStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNameStudentActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StudentDialog dialog = new StudentDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCreate;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTextField TxtBrithday;
    private javax.swing.JTextField TxtIDStudent;
    private javax.swing.JTextField TxtNameStudent;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JCheckBox rdFemale;
    private javax.swing.JCheckBox rdMale;
    private javax.swing.JTable tbStudent;
    private javax.swing.JTextArea txtAddress;
    // End of variables declaration//GEN-END:variables
}
